# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-11-17 14:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 17, 14, 7, 58, 952121, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='card',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
