# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-11-17 14:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_auto_20191117_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BU', 'Bug'), ('FR', 'Feature Request'), ('MA', 'Marketing'), ('v2', 'v2.0'), ('EN', 'Enhancement'), ('DE', 'Design')], default='BU', max_length=3)),
                ('color', models.CharField(default='#007bff', max_length=7)),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 17, 14, 22, 52, 839078, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='card',
            name='tag',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kanban.Tag'),
        ),
    ]
