# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-11-17 14:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_auto_20191117_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 17, 14, 29, 42, 225577, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='card',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='kanban.Tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('BU', 'Bug'), ('FR', 'Feature Request'), ('MA', 'Marketing'), ('V2', 'v2.0'), ('EN', 'Enhancement'), ('DE', 'Design')], default='BU', max_length=3),
        ),
    ]
