# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-11-17 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0005_auto_20191117_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
