# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-24 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_url', '0002_profile_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='extra',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
