# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-10 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mini_url', '0003_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='text',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
