# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-24 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_url', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MiniUrl',
        ),
    ]
