# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-10 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_url', '0004_todo_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
